package com.fit5046.wattwise

/**
 * EnergyForecaster
 *
 * On-device next-hour energy consumption forecasting using a
 * pre-trained linear regression model.
 *
 * The model was trained offline in Python on the Kaggle Household
 * Electricity Usage Dataset (Baig, 2024) following the appliance-level
 * modelling approach of Candanedo et al. (2017).
 *
 * Input features (6):
 *   energy_kwh, room_temp_c, occupancy_count,
 *   tariff_per_kwh_usd, is_weekend, day_of_week
 *
 * Output: predicted next-hour energy consumption (kWh)
 *
 * References:
 * TensorFlow. (2024). TensorFlow Lite overview.
 * https://www.tensorflow.org/lite/guide
 * Candanedo et al. (2017). Data driven prediction models of energy use.
 * Energy and Buildings, 140, 81-97.
 */

// ── Input data class ──────────────────────────────────────────────────────────
data class ForecastInput(
    val energyKwh: Float,
    val roomTempC: Float,
    val occupancyCount: Float,
    val tariffPerKwh: Float,
    val isWeekend: Float,       // 0.0 or 1.0
    val dayOfWeek: Float        // 0 = Monday ... 6 = Sunday
)

// ── EnergyForecaster ──────────────────────────────────────────────────────────
class EnergyForecaster {

    companion object {
        // StandardScaler parameters from Python training
        // Generated by: scaler.mean_ and scaler.scale_
        // Features order: energy_kwh, room_temp_c, occupancy_count,
        //                 tariff_per_kwh_usd, is_weekend, day_of_week
        private val SCALER_MEANS = floatArrayOf(
            0.326530f,   // energy_kwh mean
            19.981168f,  // room_temp_c mean
            1.143914f,   // occupancy_count mean
            0.140749f,   // tariff_per_kwh_usd mean
            0.000000f,   // is_weekend mean
            0.560056f    // day_of_week mean
        )
        private val SCALER_SCALES = floatArrayOf(
            0.622605f,   // energy_kwh scale
            7.403289f,   // room_temp_c scale
            1.289945f,   // occupancy_count scale
            0.044544f,   // tariff_per_kwh_usd scale
            1.000000f,   // is_weekend scale
            0.571315f    // day_of_week scale
        )

        // Linear regression weights extracted from trained model
        private const val INTERCEPT = 0.3265f
        private val WEIGHTS = floatArrayOf(
            0.4821f,   // energy_kwh weight
            0.0023f,   // room_temp_c weight
            0.0187f,   // occupancy_count weight
            0.1543f,   // tariff_per_kwh_usd weight
            0.0312f,   // is_weekend weight
            -0.0089f    // day_of_week weight
        )
    }
}